name: Update EHI Tables

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00

jobs:
  update-ehi-tables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@main
      with:
        deno-version: '1.x'

    - name: Install dependencies and run setup.sh
      run: ./setup.sh
      
    - name: Calculate hash of tables.zip
      id: hash
      run: |
        echo "HASH=$(sha256sum tables.zip | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Cache hash
      uses: actions/cache@v2
      with:
        path: .hash-cache
        key: ${{ steps.hash.outputs.HASH }}

    - name: Check if tables.zip has changed
      id: check-change
      run: |
        mkdir -p .hash-cache
        LAST_HASH=$(cat .hash-cache/last-hash 2>/dev/null || echo "")
        CURRENT_HASH="${{ steps.hash.outputs.hash }}"
        if [ "$LAST_HASH" != "$CURRENT_HASH" ]; then
          echo "tables.zip has changed"
          echo "CHANGED=true" >> $GITHUB_OUTPUT
          echo $CURRENT_HASH > .hash-cache/last-hash
        else
          echo "tables.zip has not changed"
          echo "CHANGED=false" >> $GITHUB_OUTPUT
        fi

    - name: Archive output as an artifact
      if: steps.check-change.outputs.CHANGED == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./output
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "index.tgz"
        omitBody: true          
    - name: Deploy to GitHub Pages
      if: steps.check-change.outputs.CHANGED == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
